In [1]:
price = [100,200,300,400,500]
print(price)

[100, 200, 300, 400, 500]


In [3]:
price = [100,200,300,400,500]
print(price)

new_P = []

for i in price:
    new_P.append(i+10)

print(new_P)

[100, 200, 300, 400, 500]
[110, 210, 310, 410, 510]


In [5]:
import numpy as np

price = np.array([100,200,300,400,500])
print(price)
new_Price = price+10
print(new_P)

[100 200 300 400 500]
[110, 210, 310, 410, 510]


In [6]:
new_Price = price*10
print(new_Price)

[1000 2000 3000 4000 5000]


In [7]:
sales = np.array([10, 20, 30, 40, 50])

revenue = sales * 100

print(revenue)

[1000 2000 3000 4000 5000]


In [8]:
a = [10 , 20 , 30 , 40 , 50]

b = np.array(a)

print(b)

[10 20 30 40 50]


In [9]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [11]:
arr = np.zeros([3,4])
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
arr = np.ones([3,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [15]:
arr = np.arange(5,11)
print(arr)

[ 5  6  7  8  9 10]


In [16]:
arr = np.arange(0,10,3)
print(arr)

[0 3 6 9]


In [20]:
arr = np.linspace(0, 10, 5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [23]:
arr1 = np.array([10 , 20 , 30 , 40 , 50])

print(arr1)
print(arr1.ndim)

[10 20 30 40 50]
1


In [25]:
arr2 = np.array([
    [10 , 20 , 30],
    [40 , 50 , 60]
])

print(arr2)
print(arr2.ndim)

[[10 20 30]
 [40 50 60]]
2


In [26]:
print(arr2.shape)

(2, 3)


In [29]:
arr3 = np.array([
    [
        [10 , 20 , 30],
        [40, 50 , 60]
    ],
    [
        [70 , 80 , 90],
        [100 , 110 , 120]
    ]
])

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
3
(2, 2, 3)


In [30]:
print(arr1.size)
print(arr2.size)
print(arr3.size)

5
6
12


In [31]:
print(arr3.dtype)

int64


In [32]:
arr = np.array([True, False, True])

print(arr.dtype)

bool


In [34]:
ar1 = np.array([1 , 2 , 3 , 4 , 5 , 6 ])
print(ar1)

b = ar1.reshape(2,3)
print(b)
print(b.shape)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [35]:
ar1 = np.array([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 ,10 , 11 , 12])
print(ar1)

b = ar1.reshape(2,2,3)
print(b)
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [39]:
data = np.arange(24)

b = data.reshape(4 , -1)
print(b)
print(b.shape)
print(b.dtype)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
int64


In [40]:
a = np.arange(24)

b = a.reshape(2, 3, -1)

print(b.shape)

(2, 3, 4)


In [41]:
a = np.array([10 , 20 , 30 , 40 , 50])

print(a[1])

20


In [42]:
print(a[-1])

50


In [43]:
print(a[-2])

40


In [47]:
b = np.array([
    [10 , 20 , 30],
    [40 , 50 , 60]
])
print(b[1,0])
print(b[0,-1])
print(b[1,1])
print(b[1,-1])
print(b[0,0])

40
30
50
60
10


In [ ]:
b = np.array([10 , 20 , 30 , 40 , 50 , 60])
print(b[1:4])

[20 30 40]


In [50]:
print(b[::2])

[10 30 50]


In [51]:
print(b[:5])

[10 20 30 40 50]


In [52]:
print(b[-2])

50


In [53]:
print(b[-2:])

[50 60]


In [54]:
a = np.array([
    [1 , 2 , 3],
    [4 , 5 , 6]
])

print(a[1,2])

6


In [55]:
print(a[1,:])

[4 5 6]


In [59]:
print(a[:,1])
print(a[:,2])
print(a[1])
a[1]

[2 5]
[3 6]
[4 5 6]


array([4, 5, 6])

In [62]:
print(a[0:2 , 1:3])

[[2 3]
 [5 6]]


In [63]:
a = np.array([100 , 200 , 300 , 400 , 500 , 150])

a > 200


array([False, False,  True,  True,  True, False])

In [64]:
a[a>200]

array([300, 400, 500])

In [66]:
a[(a>200) & (a<400)]

array([300])

In [68]:
print(a[(a>200) & (a<500)])

[300 400]


In [69]:
(a>200) & (a<500)

array([False, False,  True,  True, False, False])

In [71]:
print(a[(a<200) | (a>500)])

[100 150]


In [72]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("\na + b:", a + b)
print("a * b:", a * b)
print("b / a:", b / a)


a + b: [11 22 33 44]
a * b: [ 10  40  90 160]
b / a: [10. 10. 10. 10.]


In [73]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [75]:
a = np.array([100, 200, 300, 400, 500])

a.sum()



np.int64(1500)

In [76]:
a.mean()


np.float64(300.0)

In [77]:
a.max()


np.int64(500)

In [78]:
a.min()


np.int64(100)

In [79]:
a.std()


np.float64(141.4213562373095)

In [80]:
a.var()

np.float64(20000.0)

In [100]:
a = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
a.sum(axis=0)

array([150, 180, 210, 240])

In [96]:
a.sum(axis=1)

array([100, 260, 420])

In [97]:
a.mean(axis=0)


array([50., 60., 70., 80.])

In [101]:
a.max(axis=1)



array([ 40,  80, 120])

In [102]:
a.min(axis=0)

array([10, 20, 30, 40])

In [90]:
a.std(axis=1)

array([11.18033989, 11.18033989, 11.18033989])

In [91]:
a.max(axis=0)

array([ 90, 100, 110, 120])

In [103]:
a = np.array([10, 20, 30])
b = np.array([2, 3, 4])

np.dot(a, b)

np.int64(200)

In [104]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

A @ B

array([[19, 22],
       [43, 50]])

In [105]:
products = np.array(["Pen", "Book", "Bag", "Bottle"])
quantity = np.array([10, 5, 3, 8])
price = np.array([20, 100, 500, 150])

revenue = quantity * price

print("Products:", products)
print("Quantity:", quantity)
print("Price:", price)
print("Revenue:", revenue)

print("\nTotal sales:", np.sum(revenue))
print("Highest product revenue:", np.max(revenue))

# Products generating at least ₹500 revenue
mask = revenue >= 500
print("\nProducts with revenue >= ₹500:", products[mask])
print("Their revenue:", revenue[mask])

Products: ['Pen' 'Book' 'Bag' 'Bottle']
Quantity: [10  5  3  8]
Price: [ 20 100 500 150]
Revenue: [ 200  500 1500 1200]

Total sales: 3400
Highest product revenue: 1500

Products with revenue >= ₹500: ['Book' 'Bag' 'Bottle']
Their revenue: [ 500 1500 1200]
